name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: DockerHub Login
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Image
      run: |
        docker build . --file Dockerfile --tag x10102/translatordb:latest
    - name: Push Image to DockerHub
      run: |
        docker push x10102/translatordb
